### ISSUE TITLE
code of computing TP F Rate and FP E Rate

### ISSUE THREAD

**Issue by LiewFeng** [Fangyi-Chen/SQR#10]
Hi, @Fangyi-Chen , could you kindly share the code of computing TP F Rate and FP E Rate? Lots of thanks!

**Comment by Fangyi-Chen** [comment]
Hi,

Yes. The code is not an elegant read, but please leave your email there or send me an email and I will share you. Thanks.

**Comment by yuzitian** [comment]
Hello, I also want to address the code raised in the question. I would greatly appreciate it if you could share it with me. My email is: yuzitian007@gmail.com.

**Comment by LiewFeng** [comment]
Hi,
Thanks. My email is liufeng20@mails.ucas.ac.cn.

**Comment by Fangyi-Chen** [comment]
Please check this

https://drive.google.com/drive/folders/1-FAfN7Z_SwL1nopoqH7BE3iLU57SjtB-?usp=sharing

**Comment by yuzitian** [comment]
Thanks a lot for your code and advice！！

**Comment by LiewFeng** [comment]
Thanks！
